import type { Metadata, Viewport } from "next";
import { Geist } from "next/font/google";
import { JetBrains_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import VersionChecker from "@/app/components/VersionChecker";
import ToastProvider from "@/app/components/ToastProvider";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KG Tracker",
  description: "Keuschheitsgürtel Tracking",
  manifest: "/manifest.webmanifest",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "KG Tracker",
  },
  icons: {
    icon: "/icon.svg",
    apple: "/icon-192.png",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: "cover",
  themeColor: "#111827",
};

// iOS splash screen definitions (generated by scripts/generate-splash.mjs)
const splashScreens = [
  { w: 320, h: 568, r: 2, src: "/splash/splash-640x1136.png" },
  { w: 375, h: 667, r: 2, src: "/splash/splash-750x1334.png" },
  { w: 414, h: 736, r: 3, src: "/splash/splash-1242x2208.png" },
  { w: 375, h: 812, r: 3, src: "/splash/splash-1125x2436.png" },
  { w: 414, h: 896, r: 2, src: "/splash/splash-828x1792.png" },
  { w: 414, h: 896, r: 3, src: "/splash/splash-1242x2688.png" },
  { w: 360, h: 780, r: 3, src: "/splash/splash-1080x2340.png" },
  { w: 390, h: 844, r: 3, src: "/splash/splash-1170x2532.png" },
  { w: 428, h: 926, r: 3, src: "/splash/splash-1284x2778.png" },
  { w: 393, h: 852, r: 3, src: "/splash/splash-1179x2556.png" },
  { w: 430, h: 932, r: 3, src: "/splash/splash-1290x2796.png" },
  { w: 810, h: 1080, r: 2, src: "/splash/splash-1620x2160.png" },
  { w: 820, h: 1180, r: 2, src: "/splash/splash-1640x2360.png" },
  { w: 1024, h: 1366, r: 2, src: "/splash/splash-2048x2732.png" },
];

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <head>
        {/* iOS splash screens — portrait only */}
        {splashScreens.map(({ w, h, r, src }) => (
          <link
            key={src}
            rel="apple-touch-startup-image"
            href={src}
            media={`(device-width: ${w}px) and (device-height: ${h}px) and (-webkit-device-pixel-ratio: ${r}) and (orientation: portrait)`}
          />
        ))}
      </head>
      <body className={`${geistSans.variable} ${jetbrainsMono.variable} antialiased`}>
        <NextIntlClientProvider messages={messages}>
          <ToastProvider>
            {children}
            <VersionChecker buildDate={process.env.BUILD_DATE ?? "local"} />
            <Script id="sw-register" strategy="afterInteractive">{`
              if ('serviceWorker' in navigator && window.location.hostname !== 'localhost') {
                navigator.serviceWorker.register('/sw.js').catch(function(err) {
                  console.warn('[SW] registration failed:', err);
                });
              }
              if (navigator.clearAppBadge) {
                navigator.clearAppBadge().catch(function() {});
                document.addEventListener('visibilitychange', function() {
                  if (document.visibilityState === 'visible') {
                    navigator.clearAppBadge().catch(function() {});
                  }
                });
              }
            `}</Script>
          </ToastProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
